Work and about features included
0zedd/Portofolio pull request #2
Opened 2022-05-27 16:00 UTC by 0zedd

Added work and about sections to the mobile website portfolio

2022-05-27 16:32 UTC, Mre55 requested changes
**Hi @0zedd,**

You have done a great job so far! 💪 👏 
You still need to work on a few issues before moving on to the next project, but you're almost there!

## To highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 

## Required Changes ♻️🛠️ 
_Check the comments under the review._


<img width="430" src="https://media1.giphy.com/media/oVjOd9TEZDmSTc4x37/giphy.gif"/>


## Optional suggestions 🟡 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 16:32 UTC, Mre55 commented on index.html
> +       </header>
Kindly, remove the `header` tag here we don't need it rather we can use either the `article` tag or just a `div`. And I see in all of the images `src` you used no existing images and in the page, it's not rendering anything please add images first then use a proper path for you all images.

https://user-images.githubusercontent.com/34578631/170739762-6fc30354-e4ac-46a5-9865-979e98dd5f7f.mov

2022-05-27 16:32 UTC, Mre55 commented on index.html
> +        </section>
Please stick to the Figma design provided as much as possible and also add three more works here and make them look like the given design here I put your design along with the Figma one.

| Your Design | Figma Design |
|--------------|---------------|
| <img width="303" alt="image" src="https://user-images.githubusercontent.com/34578631/170740156-3acfe002-8550-49e4-b9dd-2f0658da5667.png"> | <img width="373" alt="image" src="https://user-images.githubusercontent.com/34578631/170740113-1fa53666-9da4-46ea-bcb3-c6169d238491.png"> |

2022-05-27 16:32 UTC, Mre55 commented on index.html
> +            </div>
The same comment goes here as the project section stick to the Figma design.

| Your Design | Figma Design |
|--------------|--------------|
| <img width="303" alt="image" src="https://user-images.githubusercontent.com/34578631/170740600-7cafb8f5-26dc-467c-9678-afdb7bf152ad.png"> | <img width="371" alt="image" src="https://user-images.githubusercontent.com/34578631/170740671-546c61ff-ca09-42e0-a539-bc609c75f748.png"> |

2022-05-28 14:57 UTC, jaflih requested changes
Hi @0zedd 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>


 ## Highlights

The Pull Request is following the GitHub Flow ✅
The README is well documented ✅
Linters are working properly ✅

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 14:57 UTC, jaflih commented on index.html
> +    <img class="circle" src="/img/circle.svg" width="1" height="15" alt="circle">
Good job for changing the path. But it still does not work. For correct it do like this (`add . before /img`):
(do this for all your image)
```
<img class="arc" src="./img/arc.svg" width="1" height="15" alt="arc">
    <img class="bar" src="./img/bar.svg" width="1" height="15" alt="bar">
    <img class="c" src="./img/c.svg" width="1" height="15" alt="curve">
    <img class="circle" src="./img/circle.svg" width="1" height="15" alt="circle">

```

2022-05-28 14:57 UTC, jaflih commented on index.html
> +                </ul>
As said the previous reviewer, please stick to Figma:
On figma to find what styles to use, just click on the element, and on the right you will see the CSS. property (size, color ...) 

your
<img width="241" alt="image" src="https://user-images.githubusercontent.com/7243132/170830384-2d2c8cfa-76c9-4376-8d62-cf505ff42335.png">

Figma:
<img width="241" alt="image" src="https://user-images.githubusercontent.com/7243132/170830397-4c33ba49-f9aa-4b05-a231-d56338f98800.png">

2022-05-28 14:57 UTC, jaflih commented on style.css
> +}
Please stick to Figma, like said the previous reviewer

<img width="362" alt="image" src="https://user-images.githubusercontent.com/7243132/170830511-021ae72a-8a34-48df-b4ba-65f24ca55799.png">

Figma:
<img width="362" alt="image" src="https://user-images.githubusercontent.com/7243132/170830522-45ff75d2-bf27-4b58-95a2-b9cd96169776.png">

2022-05-28 14:57 UTC, jaflih commented on index.html
> +            <p class="contact_section"><a href="#">LET'S CONNECT</a></p>
Please stick to FIgma , here use the good color

<img width="166" alt="image" src="https://user-images.githubusercontent.com/7243132/170830581-582a37e4-ebb2-4ff3-831b-02b586656720.png">

Figma
<img width="166" alt="image" src="https://user-images.githubusercontent.com/7243132/170830607-1e058d21-3fc3-4a51-9e62-ef6ee6eb87b3.png">

2022-05-28 14:57 UTC, jaflih commented on style.css
> +}
Like ask the previous reviewer , please stick to Figma

<img width="382" alt="image" src="https://user-images.githubusercontent.com/7243132/170830663-a25f1155-4e19-4a34-8305-a8bdaba1f8e3.png">

Figma
<img width="340" alt="image" src="https://user-images.githubusercontent.com/7243132/170830673-dc95ba58-4343-4a07-a6a8-fc332a99df0b.png">

2022-05-28 14:57 UTC, jaflih commented on index.html
> +                    <li><a href="#"><img src="/img/time.svg" alt="date"></a></li>
[OPTIONAL] instead of using image, write the text and design it using CSS to make your project more professional

2022-05-28 20:17 UTC, bimbolabuari approved these changes
Hi @0zedd, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-28 20:19 UTC, merged