Responsive desktop feature
0zedd/Portofolio pull request #4
Opened 2022-06-09 19:34 UTC by 0zedd

This feature includes media queries to make page responsive on larger screens

2022-06-09 20:17 UTC, zieeco requested changes
Hi @0zedd 

<img src="https://media0.giphy.com/media/wA6aYAO3jH6RmUIBYs/giphy.gif"/>

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Nice design :heavy_check_mark: 
- Linters are passing :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-09 20:17 UTC, zieeco commented on style.css
> +    border: solid;
**[REQUIRED CHANGES]**

- Please, kindly remove this border to match the Figma design

2022-06-09 20:17 UTC, zieeco commented on style.css
> +    width: 1440px;
**[REQUIRED CHANGES]**

- Please, kindly adjust your styling to ensure your width is not fixed but in percentage to remove the horizontal scroll behavior to make your portfolio responsive to improve the user experience below:


https://user-images.githubusercontent.com/59397159/172931993-d6a06864-c030-4e29-a19d-45c23ed0831d.mp4

2022-06-09 20:17 UTC, zieeco commented on style.css
> +
**[REQUIRED CHANGES]**

- Please, kindly ensure that **ALL** your social media icons have the same width to match the Figma design below:

*figma*
![iconss](https://user-images.githubusercontent.com/59397159/172932738-39602f52-0296-4c9b-813f-e170c9379958.png)

*your design*
![icons](https://user-images.githubusercontent.com/59397159/172932743-377163cf-a317-423a-bd94-7243d9ccea26.png)

2022-06-09 20:17 UTC, zieeco commented on style.css
> +  }
**[REQUIRED CHANGES]**

- Please, kindly ensure you've used the correct font family on all the paragraphs text to match the Figma design below:

*figma*
![right-fonts](https://user-images.githubusercontent.com/59397159/172933234-0163a073-ed4a-42b5-9505-8c7fe658fb92.png)

*your's*
![right-font](https://user-images.githubusercontent.com/59397159/172933237-b448dbdd-4f82-48a8-a7d5-cab9cfe10489.png)

2022-06-09 20:17 UTC, zieeco commented on style.css
> +
**[REQUIRED CHANGES]**

- Please, kindly use the correct padding, and add the correct color and background to all the buttons to indicate the interaction of hover, active, enabled, and disabled to match the Figma design as you've used another background color and the other states of the buttons haven't been implemented yet . see the image below:

![buton](https://user-images.githubusercontent.com/59397159/172934090-cfdc0d32-80cc-4261-9362-197ad6da053c.png)

2022-06-09 20:17 UTC, zieeco commented on style.css
>    flex-direction: column;
**[REQUIRED CHANGES]**

- Please, kindly try reducing the height to reduce the too much space to match the Figma design below:

*figma*
![small-space](https://user-images.githubusercontent.com/59397159/172935202-19a7762d-13f4-4095-8243-43c487321d6b.png)

*your design*
![big-space](https://user-images.githubusercontent.com/59397159/172935208-a8b87d7d-7931-4239-937c-9a3d6a7e324c.png)

2022-06-09 20:17 UTC, zieeco commented on style.css
> +
**[REQUIRED CHANGES]**

- Please, kindly improve your styling on each skill to match the Figma design as much as you can below:

*your design*
![skillss-s](https://user-images.githubusercontent.com/59397159/172935961-b48faeb0-c5a2-4995-b656-749a969c175a.png)


*figma*
![skills](https://user-images.githubusercontent.com/59397159/172935967-76c136d6-65f0-4c3c-8388-4b33988d3360.png)

2022-06-11 12:12 UTC, topeogunleye requested changes
> # Changes Required 
> ### Hi @0zedd,
> Nice job, you are almost there.
> 
> ![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
> * [ ]  Please check my inline comments.
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-11 12:12 UTC, topeogunleye commented on style.css
> +  .abt_icn {
- [ ] As suggested by the previous reviewer, I kindly suggest that you ensure that ALL your social media icons have the same width as the Figma design below:

| Your Design  | Template Design |
| ------------- | ------------- |
| ![Screenshot from 2022-06-11 12-49-18](https://user-images.githubusercontent.com/52934128/173186828-e00d002a-bba5-4106-a0c1-79dd2a603053.png) | ![Screenshot from 2022-06-11 12-56-52](https://user-images.githubusercontent.com/52934128/173186886-a3dfb2ea-2325-4a75-862a-17221548e213.png) |

2022-06-11 12:12 UTC, topeogunleye commented on style.css
- [ ] As suggested by the previous reviewer,  I kindly suggest that you make use of the font used in your template design which is [poppins](https://fonts.google.com/specimen/Poppins). 

You can import Poppins into your CSS file by writing this at the top of your CSS file:
`@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap');
`

2022-06-11 12:12 UTC, topeogunleye commented on style.css
>  button {
- [ ] As suggested by the Previous Code Reviewer, I kindly suggest that you add the different button interactions including hover, active (when it's pressed), disabled, and enable (default state) as shown in the Figma template below:

![Screenshot from 2022-04-27 19-12-50](https://user-images.githubusercontent.com/52934128/165592912-7d8bf224-8e6b-467d-bb19-cf63cd2b40fd.png)

the button on the pressed state has the `background: #2230D2;` and on hover has the `background: #6070FF;`

### EXAMPLE:
**for pressed state**
```
button:active {
   background-color: #2230D2;
}
```
**for hover state**
```
button:hover {
    background-color: #6070FF;
}
```

2022-06-11 14:11 UTC, ishimwezachee approved these changes
Hi @0zedd , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/OcZp0maz6ALok/giphy.gif"/>

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-11 14:14 UTC, merged