Mobile menu javascript
0zedd/Portofolio pull request #7
Opened 2022-06-21 13:21 UTC by 0zedd

This feature javascript was added to mobile version menu

2022-06-21 14:16 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @0zedd , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️
Your README is descriptive ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-21 14:16 UTC, leonardodiasb commented on style.css
> +}
- [ ] On some screen sizes the mobile menu is not covering the entire screen. Kindly fix that.
![image](https://user-images.githubusercontent.com/61919617/174820011-bf8cf3a1-bcd4-4760-924d-f0b15a31197b.png)

2022-06-21 14:16 UTC, leonardodiasb commented on index.html
> +            <li>Portfolio</li>
- [ ] Kindly use the font family provided by the Figma template for the mobile menu buttons.
- [ ] When the user clicks on the menu buttons they should display the correct part of the page and close the mobile menu. Kindly fix that.
![image](https://user-images.githubusercontent.com/61919617/174820940-ae6ce779-fd3d-45e8-bfc1-32284cd0cfe0.png)

2022-06-21 14:16 UTC, leonardodiasb commented on index.html
> +            <li><img class="iconx" src="./img/x.svg" alt="icon"></li>
- [ ] Kindly set the margin to match the margins and padding provided by the Figma template for your X button and your hamburger.
Your design:
![image](https://user-images.githubusercontent.com/61919617/174821488-1a7a60bd-3898-430b-8d1d-0762feef8b84.png)

Figma design:
![image](https://user-images.githubusercontent.com/61919617/174821653-8ed84f0c-9a67-40fe-80c1-942e1014c706.png)

2022-06-21 15:56 UTC, ShahierNashaat requested changes
Hi @0zedd , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-21 15:56 UTC, ShahierNashaat commented on index.html
> +            <li><a href="#port">Portfolio</a></li>
- [ ] Please implement the changes that were required by the previous code reviewer as when the click on one of the menu items the mobile menu should disappear.

2022-06-22 01:23 UTC, codepantha approved these changes
# STATUS: APPROVED 🟢 

## Hi team👋, 

Well done implementing the required changes 👏 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media4.giphy.com/media/5oGIdt1xapQ76/giphy.gif"/>

### Highlights 🎯 
✔️correct GitHub Flow 
✔️Good commit history
✔️Linter checks

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 06:50 UTC, merged